import type { EmailCampaign } from '@prisma/client';
import Link from 'next/link';
import { notFound } from 'next/navigation';

import { saveCampaignAction, sendCampaignAction, sendCampaignTestAction } from '../../actions';
import { CampaignAudienceFields } from '../../audience-fields';
import { CampaignStatusBadge } from '../../campaign-status';
import { Button } from '@/components/ui/button';
import { Card, CardDescription, CardTitle } from '@/components/ui/card';
import { Input, Label, Textarea } from '@/components/ui/field';
import { FlashMessages } from '@/components/ui/flash';
import { requirePermission } from '@/lib/auth/staff';
import { formatDateTime } from '@/lib/core/dates';
import { db } from '@/lib/db';
import { countAudience, previewCampaign } from '@/lib/email/campaigns';

export const dynamic = 'force-dynamic';

function wordsDescription(campaign: EmailCampaign): string {
  if (campaign.status === 'DRAFT') {
    return 'Plain text. Links become links in the email, and every letter carries its own unsubscribe link.';
  }

  if (campaign.status === 'SENDING') {
    return 'A send is walking the list, so the words are fixed while it runs.';
  }

  return `Sent ${campaign.sentAt ? formatDateTime(campaign.sentAt) : ''}. A sent campaign is a record of what went out, so it can no longer be edited.`;
}

/**
 * One campaign: its words, who it goes to, what it will look like, and the two
 * buttons that send it (R-083).
 *
 * The preview is generated by the same functions the sweeper uses, so what is
 * approved here is what arrives. Send is safe to press twice — every recipient
 * already written to is skipped — and the page says so rather than hiding the
 * button and hoping.
 */
export default async function CampaignPage({
  params,
  searchParams,
}: {
  params: Promise<{ campaignId: string }>;
  searchParams: Promise<{ notice?: string; problem?: string }>;
}) {
  await requirePermission('email.manage');
  const [{ campaignId }, flash] = await Promise.all([params, searchParams]);

  const campaign = await db.emailCampaign.findUnique({ where: { id: campaignId } });
  if (!campaign) notFound();

  const [lists, audienceCount, preview, sends] = await Promise.all([
    db.subscriberList.findMany({ orderBy: { name: 'asc' } }),
    countAudience(campaign),
    previewCampaign(campaign),
    db.emailCampaignSend.count({ where: { campaignId } }),
  ]);

  const isDraft = campaign.status === 'DRAFT';

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">{campaign.name}</h1>
          <p
            className="mt-1 text-sm text-[var(--color-ink-muted)]"
            data-testid="campaign-audience"
            data-count={audienceCount}
          >
            {audienceCount} address{audienceCount === 1 ? '' : 'es'} match this audience today.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <CampaignStatusBadge status={campaign.status} data-testid="campaign-status" />
          <Link href="/admin/email" className="text-sm underline underline-offset-4">
            All campaigns
          </Link>
        </div>
      </header>

      <FlashMessages notice={flash.notice} problem={flash.problem} testIdPrefix="campaign" />

      <Card>
        <CardTitle>Words</CardTitle>
        <CardDescription>{wordsDescription(campaign)}</CardDescription>

        <form action={saveCampaignAction} className="mt-4 grid gap-4">
          <input type="hidden" name="campaignId" value={campaign.id} />

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <Label htmlFor="name">Name</Label>
              <Input id="name" name="name" defaultValue={campaign.name} disabled={!isDraft} />
            </div>
            <div>
              <Label htmlFor="subject">Subject</Label>
              <Input id="subject" name="subject" defaultValue={campaign.subject} disabled={!isDraft} />
            </div>
          </div>

          <CampaignAudienceFields lists={lists} selected={campaign} />

          <div>
            <Label htmlFor="body">Message</Label>
            <Textarea
              id="body"
              name="body"
              rows={8}
              defaultValue={campaign.body}
              disabled={!isDraft}
            />
          </div>

          {isDraft ? (
            <div>
              <Button type="submit" variant="secondary">
                Save draft
              </Button>
            </div>
          ) : null}
        </form>
      </Card>

      <Card>
        <CardTitle>Preview</CardTitle>
        <CardDescription>Exactly what one recipient gets, letterhead included.</CardDescription>
        <p className="mt-3 text-sm font-medium">{preview.subject}</p>
        <pre
          className="mt-2 whitespace-pre-wrap rounded-md bg-[var(--color-surface-muted)] p-3 text-sm"
          data-testid="campaign-preview"
        >
          {preview.text}
        </pre>
      </Card>

      <Card>
        <CardTitle>Send</CardTitle>
        <CardDescription>
          A test goes to one address and changes nothing. Sending queues one message per recipient;
          anybody already written to for this campaign is skipped, so pressing Send again is safe.
          {campaign.status === 'SENDING'
            ? ' This campaign is marked as sending: either a send is running now, or one stopped part-way. Pressing Send again picks up whoever was missed.'
            : ''}
        </CardDescription>

        <form action={sendCampaignTestAction} className="mt-4 flex flex-wrap items-end gap-3">
          <input type="hidden" name="campaignId" value={campaign.id} />
          <div className="min-w-64">
            <Label htmlFor="destination">Test address</Label>
            <Input id="destination" name="destination" type="email" required />
          </div>
          <Button type="submit" variant="secondary">
            Send test
          </Button>
        </form>

        <form action={sendCampaignAction} className="mt-6 border-t border-[var(--color-line)] pt-4">
          <input type="hidden" name="campaignId" value={campaign.id} />
          <p className="mb-2 text-sm text-[var(--color-ink-muted)]" data-testid="campaign-sends">
            {sends} recipient{sends === 1 ? '' : 's'} have this campaign already.
          </p>
          <Button type="submit">{sends === 0 ? 'Send to the list' : 'Send to anyone new'}</Button>
        </form>
      </Card>
    </div>
  );
}
