import 'server-only';

import type { EmailCampaign, NewsletterSubscriber, Prisma } from '@prisma/client';
import { z } from 'zod';

import { isUniqueViolation } from '../core/prisma';
import { failure, ok, type Result } from '../core/result';
import { db } from '../db';
import { env } from '../env';
import { CAPTURE_SOURCES } from '../messaging/capture';
import { NEWSLETTER_PREFERENCE_KEYS, type NewsletterPreference } from '../newsletter/preferences';
import { createUnsubscribeToken } from '../newsletter/tokens';
import {
  addResults,
  queueMessage,
  EMPTY_OUTBOX_RESULT,
  type OutboxResult,
} from '../notifications/outbox';
import { readEmailBranding, renderBrandedHtml } from './branding';
import { sendOneOffEmail } from './one-off';

/**
 * Newsletters (R-083, R-084).
 *
 * A campaign is drafted, previewed, test-sent to one address, and only then
 * sent to its list. Sending does not mail anybody directly: it writes one
 * outbox row per subscriber and lets the sweeper carry them, so a campaign to
 * four thousand people is not one HTTP request that must not fail.
 *
 * Pressing Send twice is the case this is built around. Each recipient gets an
 * `EmailCampaignSend` row inside the same transaction as their outbox row, and
 * the unique pair `(campaignId, subscriberId)` is what makes the second press,
 * a double-clicked form or a resumed half-finished send produce nothing.
 */
export const CAMPAIGN_NOT_FOUND = 'campaign_not_found';
export const CAMPAIGN_INVALID = 'campaign_invalid';
export const CAMPAIGN_NO_SENDER = 'campaign_no_sender';

const campaignSchema = z.object({
  name: z.string().trim().min(1, 'Give the campaign a name so it can be found again.').max(120),
  subject: z.string().trim().min(1, 'An email needs a subject line.').max(160),
  body: z.string().trim().min(1, 'There is nothing to send yet.').max(20_000),
  listId: z
    .string()
    .trim()
    .transform((value) => (value === '' ? null : value))
    .nullable(),
  preferenceKey: z
    .string()
    .trim()
    .transform((value) => (value === '' ? null : value))
    .nullable()
    .refine(
      (value) => value === null || NEWSLETTER_PREFERENCE_KEYS.includes(value as NewsletterPreference),
      'That is not one of the three newsletter preferences.',
    ),
});

export type CampaignInput = z.input<typeof campaignSchema>;

export async function saveCampaign(
  campaignId: string | null,
  input: CampaignInput,
  staffUserId: string,
): Promise<Result<EmailCampaign>> {
  const parsed = campaignSchema.safeParse(input);
  if (!parsed.success) return failure(CAMPAIGN_INVALID, parsed.error.issues[0].message);

  if (!campaignId) {
    return ok(
      await db.emailCampaign.create({
        data: { ...parsed.data, createdByStaffUserId: staffUserId },
      }),
    );
  }

  const existing = await db.emailCampaign.findUnique({ where: { id: campaignId } });
  if (!existing) return failure(CAMPAIGN_NOT_FOUND, 'That campaign no longer exists.');

  // A sent letter is a record of what went out. Editing it would rewrite what
  // four thousand people were told they had read.
  if (existing.status !== 'DRAFT') {
    return failure(CAMPAIGN_INVALID, 'This campaign has already been sent, so its words are fixed.');
  }

  return ok(await db.emailCampaign.update({ where: { id: campaignId }, data: parsed.data }));
}

/**
 * Who this letter goes to.
 *
 * A list narrows the audience and the preference flag narrows it again — a
 * list can never be a way around an opt-out — and only live subscriptions are
 * ever included.
 */
export function audienceFilter(campaign: {
  listId: string | null;
  preferenceKey: string | null;
}): Prisma.NewsletterSubscriberWhereInput {
  return {
    status: 'SUBSCRIBED',
    ...(campaign.listId ? { listMemberships: { some: { listId: campaign.listId } } } : {}),
    ...(campaign.preferenceKey ? { [campaign.preferenceKey]: true } : {}),
  };
}

export function countAudience(campaign: {
  listId: string | null;
  preferenceKey: string | null;
}): Promise<number> {
  return db.newsletterSubscriber.count({ where: audienceFilter(campaign) });
}

export type CampaignPreview = { subject: string; text: string; html: string };

/**
 * What one recipient will actually receive, letterhead and manage link
 * included. The preview is generated by the same two functions the sweeper
 * uses, so what staff approve is what goes out.
 */
export async function previewCampaign(
  campaign: Pick<EmailCampaign, 'subject' | 'body'>,
  sampleToken = 'preview-token',
): Promise<CampaignPreview> {
  const branding = await readEmailBranding();
  const text = bodyWithManageLink(campaign.body, sampleToken);

  return {
    subject: campaign.subject,
    text,
    html: renderBrandedHtml(branding, { subject: campaign.subject, body: text }),
  };
}

/**
 * One copy to one address, without touching the campaign's send records
 * (R-090). A test is a rehearsal: it must not be able to mark a subscriber as
 * already written to, or the real send would skip them.
 */
export async function sendCampaignTest(
  campaign: Pick<EmailCampaign, 'subject' | 'body'>,
  destination: string,
): Promise<Result<{ provider: string }>> {
  const preview = await previewCampaign(campaign);

  return sendOneOffEmail({
    destination,
    subject: `[test] ${preview.subject}`,
    body: preview.text,
    source: CAPTURE_SOURCES.campaignTest,
  });
}

/**
 * A list is walked in pages rather than loaded whole: four thousand
 * subscribers is four thousand rows held in memory for as long as the send
 * takes, and the send is one sequential write per person.
 */
const RECIPIENT_PAGE_SIZE = 500;

export async function sendCampaign(campaignId: string): Promise<Result<OutboxResult>> {
  const campaign = await db.emailCampaign.findUnique({ where: { id: campaignId } });
  if (!campaign) return failure(CAMPAIGN_NOT_FOUND, 'That campaign no longer exists.');

  await db.emailCampaign.update({ where: { id: campaign.id }, data: { status: 'SENDING' } });

  let summary = EMPTY_OUTBOX_RESULT;

  try {
    for await (const subscriber of eachRecipient(campaign)) {
      summary = addResults(summary, await queueOneRecipient(campaign, subscriber));
    }
  } catch (error) {
    // SENDING is a claim that a loop is running. Once this one has thrown,
    // nothing is going to finish it, and a campaign left in that state can be
    // neither edited nor re-sent. Back to DRAFT: every recipient already
    // written to is skipped on the next press, so pressing Send again resumes
    // rather than repeats.
    await db.emailCampaign.update({ where: { id: campaign.id }, data: { status: 'DRAFT' } });
    throw error;
  }

  await db.emailCampaign.update({
    where: { id: campaign.id },
    data: {
      status: 'SENT',
      sentAt: campaign.sentAt ?? new Date(),
      recipientCount: await db.emailCampaignSend.count({ where: { campaignId: campaign.id } }),
    },
  });

  return ok(summary);
}

async function* eachRecipient(campaign: EmailCampaign): AsyncGenerator<NewsletterSubscriber> {
  let cursor: string | undefined;

  for (;;) {
    const page = await db.newsletterSubscriber.findMany({
      where: audienceFilter(campaign),
      orderBy: [{ subscribedAt: 'asc' }, { id: 'asc' }],
      take: RECIPIENT_PAGE_SIZE,
      ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
    });

    for (const subscriber of page) yield subscriber;

    if (page.length < RECIPIENT_PAGE_SIZE) return;
    cursor = page[page.length - 1].id;
  }
}

/**
 * The send row and the outbox row are written together or not at all: a send
 * row with no message would tell every rerun that this person has already been
 * written to, and a message with no send row would let a rerun write to them
 * again.
 */
async function queueOneRecipient(
  campaign: EmailCampaign,
  subscriber: NewsletterSubscriber,
): Promise<OutboxResult> {
  const dedupeKey = `campaign:${campaign.id}:${subscriber.id}`;

  try {
    return await db.$transaction(async (tx) => {
      const queued = await queueMessage(
        {
          channel: 'EMAIL',
          kind: 'campaign.send',
          destination: subscriber.email,
          subject: campaign.subject,
          body: bodyWithManageLink(campaign.body, createUnsubscribeToken(subscriber.id)),
          dedupeKey,
        },
        tx,
      );

      if (queued.queued === 0) return queued;

      // The send row goes in second and rolls the message back if it collides.
      // That is what covers the one case the outbox alone cannot: a purge has
      // deleted last year's delivered message, so the dedupe key is free again
      // while the proof that this person was written to is not.
      await tx.emailCampaignSend.create({
        data: {
          campaign: { connect: { id: campaign.id } },
          subscriber: { connect: { id: subscriber.id } },
          message: { connect: { dedupeKey } },
        },
      });

      return queued;
    });
  } catch (error) {
    if (isUniqueViolation(error)) return { ...EMPTY_OUTBOX_RESULT, alreadySent: 1 };
    throw error;
  }
}

/**
 * Every newsletter carries its own way out (R-123). The link is the same
 * signed token the preferences page reads, so a recipient with no account can
 * still change their mind from the email in front of them.
 */
function bodyWithManageLink(body: string, token: string): string {
  const manageUrl = new URL('/newsletter/manage', env.APP_URL);
  manageUrl.searchParams.set('token', token);

  return `${body.trim()}\n\nChange what we send you, or unsubscribe: ${manageUrl.toString()}`;
}
